# Generated by Django 4.2.3 on 2023-08-20 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Posts",
        ),
    ]
