# Generated by Django 4.2.3 on 2023-08-21 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "network",
            "0007_remove_userprofile_followers_alter_userprofile_user_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="user_name",
        ),
    ]
