# Generated by Django 4.2.3 on 2023-08-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0009_rename_followers_userprofile_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
